# Generated by Django 4.2.5 on 2023-10-24 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['-created_at']},
        ),
    ]
